import Head from 'next/head';
import { useSelector } from 'react-redux';

import { RootState } from '../store';
import RequisitionDetails from '../components/requisitionDetails';
import JobDetails from '../components/jobDetails';
import InterviewSettings from '../components/interviewSettings';

export default function Home() {
	const { formPage } = useSelector((state: RootState) => state.form);
	return (
		<>
			<Head>
				<title>Multi page form - TS</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				{formPage === 1 ? (
					<RequisitionDetails />
				) : formPage === 2 ? (
					<JobDetails />
				) : (
					<InterviewSettings />
				)}
			</main>
		</>
	);
}
